In [1]:
import numpy as np

a = np.zeros(3)
a

array([0., 0., 0.])

In [2]:
z = np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
z.shape

(10,)

In [5]:
z.shape = (10, 1)
z

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [15]:
z = np.ones(10)
z

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
z = np.epmty(3)
z

AttributeError: module 'numpy' has no attribute 'epmty'

In [17]:
z = np.empty(3)
z

array([0., 0., 0.])

In [13]:
z = np.linspace(2, 10, 5) #From 2 to 10, with 5 elements

In [14]:
z = np.array([10, 20]) #ndarray from Python list
z

array([10, 20])

In [18]:
a_list = [1,2,3,4,5,6,7]
z = np.array([a_list])
z

array([[1, 2, 3, 4, 5, 6, 7]])

In [19]:
type(z)

numpy.ndarray

In [21]:
b_list = [[9,8,7,6,5,4,3],[1,2,3,4,5,6,7]]
z = np.array([b_list])
z

array([[[9, 8, 7, 6, 5, 4, 3],
        [1, 2, 3, 4, 5, 6, 7]]])

In [23]:
z.shape
?z.shape

In [24]:
np.random.seed(0)
z1 = np.random.randint(10, size = 6)
z1

array([5, 0, 3, 3, 7, 9])

In [25]:
z1[0]

5

In [26]:
z1[0:2]

array([5, 0])

In [27]:
z1[-1]

9

In [29]:
# from skimage import io
# photo = io.imread('york_minester.jpg')
# type(photo)

In [30]:
# photo.shape

In [31]:
import matplotlib.pyplot as plt

In [34]:
# plt.imshow(photo)

In [35]:
# plt.imshow(photo[::-1])

In [36]:
# plt.imshow(photo[:, ::-1])

In [38]:
# plt.imshow(photo[50:150, 150:280])

In [1]:
# plt.imshow(photo[:: 2, ::2])

In [3]:
# photo
# photo_sin = np.sin(photo)
# photo_sin

In [3]:
# print(np.sum(photo))
# print(np.prod(photo))
# print(np.mean(photo))
# print(np.std(photo))
# print(np.var(photo))
# print(np.min(photo))
# print(np.max(photo))
# print(np.argmin(photo))
# print(np.argmax(photo))

In [11]:
# z = np.array([1, 2, 3, 4, 5])

In [5]:
# z < 3

In [6]:
# z > 3

In [7]:
# z[z > 3]

In [8]:
# photo_masked = np.where(photo > 100, 255, 0)

In [10]:
# plt.imshow(photo_masked)

In [16]:
# a_array = np.array([1,2,3,4,5])
# b_array = np.array([6,7,8,9,10])

In [13]:
# a_array + b_array

In [17]:
# a_array + 30

In [19]:
# a_array * b_array

In [20]:
# a_array * 10

In [21]:
# a_array @ b_array

In [22]:
# plt.imshow(photo[:,:,0].T)

In [24]:
# x = np.array([2, 1, 4, 3, 5])
# np.sort(x)